#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$commands = require_once __DIR__ . '/config/commands.php';

foreach ($commands as $command) {
	$application->add(new $command());
}

$application->run();