#!/usr/bin/env php
<?php

/**
 * Bootstrapping the application
 */
require_once __DIR__ . '/bootstrap/bootstrap.php';

/**
 * Gets the Console Application
 */
$application = new Symfony\Component\Console\Application();

/**
 * Gets the registered commands and adds them to the application.
 */
$commands = getConfig('commands');

foreach ($commands as $command) {
    $application->add(new $command());
}

/**
 * Run the application.
 */
$application->run();
